git:
  quiet: true

dist: bionic
language: c
compiler:
  - gcc
os: linux
addons:
  apt:
    packages:
      - locales
      - language-pack-de
      - re2c
      - ccache
      - mysql-server
      - libaspell-dev
      - libbz2-dev
      - libcurl4-gnutls-dev
      - libenchant-dev
      - libfreetype6-dev
      - libgmp-dev
      - libicu-dev
      - libjpeg-dev
      - libkrb5-dev
      - libonig-dev
      - libpng-dev
      - libpq-dev
      - libpspell-dev
      - libsasl2-dev
      - libsqlite3-dev
      - libsodium-dev
      - libtidy-dev
      - libwebp-dev
      - libxml2-dev
      - libxpm-dev
      - libxslt1-dev
      - libzip-dev
  coverity_scan:
    project:
      name: "twose/php-src"
      description: "none"
    notification_email: twose@qq.com
    build_command_prepend: "ENABLE_ZTS=0 ENABLE_DEBUG=1 CONFIG_ONLY=1 ./travis/compile.sh"
    build_command: "make -j4"
    branch_pattern: coverity_scan

env:
    global:
      - secure: "RM3kQ7Rque2s4sO0eiu59ow5PiF3IXLACblBm5iQzzS++WCLtQchkwV8ngP7brAtWRyYik/LGf+PRkhaH/eNX68MVJAp1tk8GPPOgNZScuGRuMEp+2BGcGlWuDLUVmBBeAGo1KSowAE0jZYwYQWKAe+87C+5mk3ntuTQMOyrQc3uIiytr1k3NSdrDKfyvYH0Exn7wNHTq9LtN/m6QvP+LyhKBFyPvT6wYOL3H4Z3csYciUuDlGCvpmIKzIM51eOFqw2h/7jRvT/mYU/upBIpDpjSXeOEMFS1GIWZ9LuVxSx95g9V+xiuOJ7sYNsaPYJuriiTEteol9i5IB2ToIGIPdv0NTwgVxyLRgHbkak0Y0+FZhxgZai6TWl9dTg8i0durd5S0XqZ5iT+iie2YITwuYCpowKvnDLlv541j1VpWb44tUZirnBDYFTBTDwZkBWeoAkMG4v6BQcdhkfmloPkzouMOxrHNGl7zxkc6Y+JSnwZEUOiSgrGs5W7rJkAPyP/HlSsGikuLlB16cDBkFn4AuvTqErmtGftEAxxKdkbtMW9hhBcWBo0JKU5afngHeRxdvNh5cae3aO1ZLRceZwkHYBXzcTjRl7b9SGypjmyCBdwmeqe0A9wz7uX6/x5XdqcPqq8gDWhUYerrfMKH8UigNU8JpDZfEiEruLmqivEpqk="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:
  - make -j4
